test:
  _target_: "sub_projects.ray_optimization.ray_optimization.RayOptimization"
  rg:
      _target_: "ray_tools.base.utils.RandomGenerator"
      seed: 42
defaults:
  - _self_
  - gauss_simulation
  - optuna
