defaults:
  - _self_
  - ray_optimizer: optuna
  - optimization_target_configuration: metrixs_real
_target_: "sub_projects.ray_optimization.ray_optimization.RayOptimization"
rg:
    _target_: "ray_tools.base.utils.RandomGenerator"
    seed: 42
logging_entity: "hzb-aos"
logging_project: "metrix_hackathon_gauss"
study_name: "test"
